"""
10Pearls AQI Predictor - dashboard

Run locally:   streamlit run app/dashboard.py
Deployed on:   Streamlit Community Cloud

Navigation
----------
Views are chosen from the sidebar rather than tabs across the top.
Streamlit's st.tabs cannot be moved into the sidebar, so this uses a
radio styled to look like a nav list - same behaviour, and it keeps the
main area free for content.

Data source
-----------
data/dashboard_snapshot.json, committed to the repo and regenerated by
the daily training workflow immediately after the models are retrained.

There is deliberately no live-fetch path. An earlier version had one,
but it could not produce anything newer: the snapshot is rebuilt from
the same models in the same run, so a live read returns the same
forecast several seconds slower. Meanwhile Hopsworks' free tier hangs
for minutes at a time, and because Streamlit blocks on the call, that
froze the whole page. Reading a committed file cannot fail.
"""

import base64
import json
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "pipeline"))

SNAPSHOT = ROOT / "data" / "dashboard_snapshot.json"
FIGURES = ROOT / "notebooks" / "figures"
SHAP_SUMMARY = ROOT / "data" / "shap_summary.json"

st.set_page_config(page_title="10Pearls AQI Predictor", page_icon="◐",
                   layout="wide", initial_sidebar_state="expanded")

# The official 10Pearls logo, embedded as base64 so it travels with the
# repo and needs no separate static-file serving.
#
# Two variants, because the supplied artwork is black on a WHITE
# background - dropped straight into the dark theme it showed as a white
# box. The build step below turns the white into transparency (deriving
# alpha from pixel darkness, so antialiased edges stay smooth) and
# recolours the ink: near-black for the light theme, white for the dark
# one. Picking a file beats a CSS invert filter, which tends to render
# grey rather than a clean white.
@st.cache_data(show_spinner=False)
def logo_tag(dark):
    """
    Cached because the encoding ran on every rerun - every theme switch,
    every view change, every radio click - and re-reading plus encoding
    15 KB each time was enough to feel like a lag. Streamlit caches per
    argument, so both variants are built once.
    """
    name = "logo_dark.png" if dark else "logo_light.png"
    path = ROOT / "app" / "assets" / name
    if not path.exists():
        return '<div class="logo-fallback">10Pearls</div>'
    data = base64.b64encode(path.read_bytes()).decode()
    return ('<img class="logo" alt="10Pearls" '
            'src="data:image/png;base64,%s">' % data)


CATEGORY_DOT = {
    "Good": "#5dcaa5", "Moderate": "#e0c060",
    "Unhealthy for Sensitive Groups": "#e09050", "Unhealthy": "#d86050",
    "Very Unhealthy": "#a070c0", "Hazardous": "#8a4040", "Unknown": "#8e8e88",
}

VIEWS = ["Overview", "Forecast", "Accuracy", "History"]


# ---------------------------------------------------------------
# Styling
# ---------------------------------------------------------------
def inject_css(dark):
    if dark:
        v = dict(bg="#0a0a0a", p1="#141414", p2="#1c1c1a",
                 ln="rgba(255,255,255,.09)", ln2="rgba(255,255,255,.18)",
                 tx="#f2f2f0", dm="#8e8e88", ft="#5c5c57",
                 hov="rgba(255,255,255,.05)")
    else:
        v = dict(bg="#f7f7f5", p1="#ffffff", p2="#efefec",
                 ln="rgba(0,0,0,.08)", ln2="rgba(0,0,0,.18)",
                 tx="#0b0b0b", dm="#5f5f5a", ft="#9a9a94",
                 hov="rgba(0,0,0,.04)")

    ac = "#8DC63F"          # 10Pearls green, used sparingly

    st.markdown(f"""<style>
    :root {{
      --bg:{v['bg']}; --p1:{v['p1']}; --p2:{v['p2']};
      --ln:{v['ln']}; --ln2:{v['ln2']}; --hov:{v['hov']};
      --tx:{v['tx']}; --dm:{v['dm']}; --ft:{v['ft']}; --ac:{ac};
    }}
    .stApp {{ background:var(--bg); color:var(--tx); }}
    [data-testid="stHeader"] {{ background:transparent; }}
    .block-container {{ padding:1.4rem 2.2rem 3rem; max-width:1500px; }}
    #MainMenu, footer {{ visibility:hidden; }}
    h1,h2,h3,h4,h5,p,span,div,label {{ color:var(--tx); }}

    /* ---- Sidebar: flat, no containers, mark sits top-left ---- */
    [data-testid="stSidebar"] {{ background:var(--p1);
                                 border-right:1px solid var(--ln); }}
    [data-testid="stSidebar"] * {{ color:var(--tx); }}
    /* Sits high and reads large, like the Claude sidebar wordmark */
    [data-testid="stSidebar"] > div:first-child {{ padding-top:.55rem; }}
    /* The logo is re-encoded and re-inserted on every theme switch, so
       there is a brief flash as the browser swaps the image. A short
       fade-and-lift on arrival turns that into an intentional
       transition rather than a stutter. */
    .logo {{ width:168px; height:auto; display:block; margin:2px 0 9px 1px;
             animation: logo-in .42s cubic-bezier(.22,1,.36,1) both; }}
    @keyframes logo-in {{
      from {{ opacity:0; transform:translateY(-5px) scale(.96); filter:blur(3px); }}
      to   {{ opacity:1; transform:translateY(0)   scale(1);   filter:blur(0);   }} }}
    .logo-fallback {{ font-size:24px; font-weight:700; letter-spacing:-1px;
                      margin:2px 0 9px 1px; }}

    /* The rest of the sidebar settles in behind it, staggered, so the
       whole panel reads as one movement instead of several. */
    .logo-sub {{ animation: rise .4s ease-out both .06s; }}
    .logo-loc {{ animation: rise .4s ease-out both .11s; }}
    [data-testid="stSidebar"] div[role="radiogroup"] {{
      animation: rise .4s ease-out both .14s; }}

    /* Cross-fade the whole page on a theme change. Without it the
       palette snaps, which reads as a glitch next to the logo fading. */
    .stApp {{ animation: theme-in .3s ease-out both; }}
    @keyframes theme-in {{ from {{ opacity:.55; }} to {{ opacity:1; }} }}
    .logo-sub {{ font-size:11px; color:var(--dm); letter-spacing:1.4px;
                 margin:0 0 3px 3px; }}
    .logo-loc {{ font-size:11px; color:var(--ft); margin:0 0 24px 3px; }}
    .logo-loc b {{ color:var(--ac); font-weight:400; }}
    .side-head {{ font-size:10px; letter-spacing:1.3px; color:var(--ft);
                  margin:20px 0 7px 3px; }}

    /* Sidebar radio, restyled as a navigation list */
    [data-testid="stSidebar"] div[role="radiogroup"] {{ gap:1px; }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label {{
      background:transparent; border:0; border-radius:8px;
      padding:8px 11px; margin:0; font-size:14px; width:100%;
      transition:background .18s; }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label:hover {{
      background:var(--hov); }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label:has(input:checked) {{
      background:var(--p2); }}
    /* Hide the radio circles - this reads as a menu, not a form */
    [data-testid="stSidebar"] div[role="radiogroup"] label > div:first-child {{
      display:none; }}

    /* Theme switch stays a visible pair of options */
    [data-testid="stSidebar"] .theme-row div[role="radiogroup"] {{
      flex-direction:row; gap:5px; }}

    /* ---- Page heading ---- */
    .page-head {{ margin-bottom:18px; animation:rise .5s ease-out both; }}
    .page-head h1 {{ font-size:31px; font-weight:600; letter-spacing:-1px;
                     margin:0 0 4px; line-height:1.1; }}
    .page-sub {{ font-size:13px; color:var(--dm); }}

    /* ---- Cards ---- */
    .card {{ background:var(--p1); border:1px solid var(--ln);
             border-radius:13px; padding:15px 17px; height:100%;
             transition:border-color .25s, transform .25s;
             animation:rise .45s ease-out both; }}
    .card:hover {{ border-color:var(--ln2); transform:translateY(-2px); }}
    .lbl {{ font-size:10px; color:var(--dm); letter-spacing:.8px; }}
    .val {{ font-size:27px; font-weight:500; letter-spacing:-1.1px;
            margin:7px 0 3px; line-height:1;
            animation:pop .5s cubic-bezier(.34,1.4,.64,1) both .18s; }}
    .sub {{ font-size:10px; color:var(--ft); }}
    .hero-num {{ font-size:52px; font-weight:500; letter-spacing:-2.5px;
                 line-height:1;
                 animation:pop .6s cubic-bezier(.34,1.4,.64,1) both .1s; }}
    .pill {{ font-size:11px; padding:4px 11px; border:1px solid var(--ln2);
             border-radius:99px; display:inline-block; }}
    .dot {{ width:7px; height:7px; border-radius:50%; display:inline-block;
            margin-right:6px; vertical-align:1px; }}
    .dot.live {{ animation:pulse 2.4s ease-in-out infinite; }}
    .alert {{ background:var(--p2); border:1px solid var(--ln2);
              border-left:3px solid #e0c060; border-radius:0 12px 12px 0;
              padding:12px 15px; font-size:13px; margin-bottom:14px;
              animation:rise .45s ease-out both; }}
    .bar-track {{ height:4px; background:var(--bg); border-radius:9px;
                  overflow:hidden; margin:8px 0 9px; }}
    .bar-fill {{ height:100%; background:var(--ac); border-radius:9px;
                 animation:grow .9s cubic-bezier(.4,0,.2,1) both .2s; }}
    .foot {{ font-size:11px; color:var(--ft); line-height:1.7; }}

    [data-testid="column"]:nth-child(2) .card {{ animation-delay:.07s; }}
    [data-testid="column"]:nth-child(3) .card {{ animation-delay:.13s; }}
    [data-testid="column"]:nth-child(4) .card {{ animation-delay:.19s; }}

    /* ---- Chart reveal ----
       Plotly cannot draw a line progressively inside Streamlit without
       adding a play button, so the container is revealed left to right
       instead. The effect is the same: the trace appears to draw itself.

       It replays whenever a chart is redrawn - switching Day +1 to
       Day +2, or changing the history range - which makes the change
       feel like a response rather than a jump cut. */
    [data-testid="stPlotlyChart"] {{
      animation: sweep 1s cubic-bezier(.4,0,.2,1) both; }}
    /* Bars grow from the left.
       Plotly frames were the obvious way to do this, but Streamlit
       renders charts with autoplay off and a hidden updatemenu button
       cannot fire itself - the bars stayed at zero. Scaling the
       container horizontally gives the same effect and cannot silently
       fail. transform-origin pins the growth to the axis, so the bars
       extend rightward from their labels rather than expanding
       outward from the middle. */
    .shap-charts [data-testid="stPlotlyChart"] {{
      animation: grow-bars .85s cubic-bezier(.34,1.12,.64,1) both .1s;
      transform-origin: left center; }}
    @keyframes grow-bars {{
      from {{ transform: scaleX(.02); opacity:.35; }}
      to   {{ transform: scaleX(1);   opacity:1;   }} }}
    @keyframes sweep {{
      from {{ clip-path: inset(0 100% 0 0); opacity:.4; }}
      to   {{ clip-path: inset(0 0 0 0);    opacity:1;  }} }}

    /* ---- Motion ---- */
    @keyframes rise {{ from{{opacity:0;transform:translateY(10px)}}
                       to{{opacity:1;transform:translateY(0)}} }}
    @keyframes pop {{ 0%{{opacity:0;transform:scale(.86)}}
                      60%{{transform:scale(1.04)}}
                      100%{{opacity:1;transform:scale(1)}} }}
    @keyframes pulse {{ 0%,100%{{opacity:1;transform:scale(1)}}
                        50%{{opacity:.45;transform:scale(1.35)}} }}
    @keyframes grow {{ from{{width:0 !important}} }}
    @media (prefers-reduced-motion: reduce) {{
      *,*::before,*::after {{ animation-duration:.01ms !important;
                              animation-iteration-count:1 !important; }}
      [data-testid="stPlotlyChart"] {{ clip-path:none !important; }} }}

    /* ---- Dialog ----
       Rendered in a portal outside .stApp, so it needs its own rules or
       it stays dark when the rest of the page turns light. */
    div[data-testid="stDialog"] > div,
    div[role="dialog"] {{ background:var(--p1) !important;
                          border:1px solid var(--ln) !important;
                          border-radius:14px !important; }}
    div[role="dialog"] * {{ color:var(--tx) !important; }}
    div[role="dialog"] strong {{ color:var(--tx) !important; }}

    .stButton>button {{ background:var(--p2); color:var(--tx);
      border:1px solid var(--ln2); border-radius:8px; font-size:13px;
      font-weight:400; width:100%; transition:all .2s; }}
    .stButton>button:hover {{ border-color:var(--ac); }}
    .stMain div[role="radiogroup"] {{ gap:5px; }}
    .stMain div[role="radiogroup"] label {{ background:var(--p1);
      border:1px solid var(--ln); border-radius:8px; padding:6px 14px;
      font-size:13px; transition:all .2s; }}
    .stMain div[role="radiogroup"] label:hover {{ border-color:var(--ln2); }}
    </style>""", unsafe_allow_html=True)


# ---------------------------------------------------------------
# Data
# ---------------------------------------------------------------
@st.cache_data(ttl=3600, show_spinner=False)
def read_shap():
    """
    The SHAP explanations, written by pipeline/11_explain.py.

    Committed as JSON plus PNGs rather than computed here: SHAP needs
    the model files and xgboost, neither of which the deployed app
    carries, and the explanations only change when the models do.
    """
    if not SHAP_SUMMARY.exists():
        return None
    with open(SHAP_SUMMARY) as f:
        return json.load(f)


@st.cache_data(ttl=3600, show_spinner=False)
def read_snapshot():
    if not SNAPSHOT.exists():
        return None
    with open(SNAPSHOT) as f:
        snap = json.load(f)

    fc = pd.DataFrame(snap["forecast"])
    fc["timestamp"] = pd.to_datetime(fc["timestamp"], utc=True)
    hi = pd.DataFrame(snap["history"])
    hi["timestamp"] = pd.to_datetime(hi["timestamp"], utc=True)

    return {
        "mode": "snapshot", "current": snap["current"], "forecast": fc,
        "daily": pd.DataFrame(snap["daily"]), "history": hi,
        "models": snap["models"],
        "predicted_from": pd.Timestamp(snap["predicted_from"]),
        "source": "snapshot &middot; " + snap["generated_at"][:16].replace("T", " "),
        "pollutant_history": snap.get("pollutant_history", {}),
    }


# ---------------------------------------------------------------
# Charts
# ---------------------------------------------------------------
def line_chart(x, y, dark, height=300, markers=True, dividers=None):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    grid = "rgba(255,255,255,.07)" if dark else "rgba(0,0,0,.09)"
    # Axis labels need real contrast, not the muted --ft grey. Plotly
    # also keeps its own default template colours unless every tickfont
    # is set explicitly, which is why the labels stayed light when the
    # page turned light.
    lab = "#8e8e88" if dark else "#4a4a46"

    lo, hi = min(y), max(y)
    pad = max((hi - lo) * 0.35, 8)
    floor = lo - pad

    fig = go.Figure()
    # Fill to the axis floor, not to zero. tozeroy reaches for y=0 while
    # the axis starts near 85, which drew a slab below the plot.
    fig.add_trace(go.Scatter(
        x=list(x) + list(x)[::-1], y=list(y) + [floor] * len(y),
        mode="lines", line=dict(width=0), fill="toself",
        fillcolor="rgba(141,198,63,.10)", hoverinfo="skip", showlegend=False))
    fig.add_trace(go.Scatter(
        x=x, y=y, mode="lines+markers" if markers else "lines",
        line=dict(color=tx, width=2, shape="spline", smoothing=0.6),
        marker=dict(size=5, color=tx),
        hovertemplate="AQI %{y}<br>%{x|%a %d %b %H:%M}<extra></extra>",
        showlegend=False))

    # No template override: template="none" strips Plotly's default axis
    # configuration along with its colours, which removed the tick labels
    # entirely. Setting every tickfont explicitly is enough to fix the
    # light-mode contrast on its own.
    fig.update_layout(
        height=height, margin=dict(l=0, r=0, t=10, b=0),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=lab, size=11),
        xaxis=dict(showgrid=False, zeroline=False, linecolor=grid,
                   tickfont=dict(color=lab, size=11),
                   title_font=dict(color=lab)),
        yaxis=dict(showgrid=True, gridcolor=grid, zeroline=False,
                   range=[floor, hi + pad],
                   tickfont=dict(color=lab, size=11),
                   title_font=dict(color=lab)),
        hoverlabel=dict(bgcolor="#1a1a1a" if dark else "#ffffff",
                        font_color=tx, bordercolor=grid))

    for d in dividers or []:
        fig.add_vline(x=d, line_width=1, line_dash="dot", line_color=grid)
    return fig


def gauge(value, dark):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    track = "rgba(255,255,255,.1)" if dark else "rgba(0,0,0,.08)"
    lab = "#8e8e88" if dark else "#4a4a46"
    fig = go.Figure(go.Indicator(
        mode="gauge+number", value=value,
        number=dict(font=dict(size=36, color=tx)),
        gauge=dict(axis=dict(range=[0, 200], tickwidth=0,
                             tickfont=dict(size=9, color=lab)),
                   bar=dict(color="#8DC63F", thickness=0.3),
                   bgcolor="rgba(0,0,0,0)", borderwidth=0,
                   steps=[dict(range=[0, 200], color=track)])))
    fig.update_layout(height=190, margin=dict(l=16, r=16, t=8, b=8),
                      paper_bgcolor="rgba(0,0,0,0)", font=dict(color=lab))
    return fig


def shap_importance_chart(block, dark):
    """
    Global importance, as a native chart rather than the matplotlib PNG
    the script also writes.

    The PNGs are still produced for the report, but embedding them here
    looked wrong: a white figure on a dark page, unable to follow the
    theme toggle and with no hover. Reading the numbers out of
    shap_summary.json instead means one source of truth and a chart that
    matches everything around it.
    """
    tx = "#f2f2f0" if dark else "#0b0b0b"
    grid = "rgba(255,255,255,.07)" if dark else "rgba(0,0,0,.09)"
    lab = "#8e8e88" if dark else "#4a4a46"

    items = list(block["global_importance"].items())[:10][::-1]
    names = [pretty_feature(k) for k, _ in items]
    vals = [v for _, v in items]

    fig = go.Figure(go.Bar(
        x=vals, y=names, orientation="h",
        marker=dict(color="#8DC63F", line=dict(color=tx, width=.4)),
        hovertemplate="%{y}<br>%{x:.2f} AQI points<extra></extra>"))
    fig.update_layout(
        height=320, margin=dict(l=0, r=10, t=6, b=30),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=lab, size=11),
        xaxis=dict(title="mean absolute SHAP value", gridcolor=grid,
                   range=[0, max(vals) * 1.08],
                   tickfont=dict(color=lab), title_font=dict(color=lab, size=10)),
        yaxis=dict(tickfont=dict(color=tx, size=11)),
        hoverlabel=dict(bgcolor="#1a1a1a" if dark else "#ffffff",
                        font_color=tx, bordercolor=grid),
        # Bars grow out from zero on first draw. Plotly needs an explicit
        # frame duration for this; without it they simply appear.
        transition=dict(duration=650, easing="cubic-out"))
    return fig


def shap_local_chart(block, dark):
    """One prediction, split into what pushed it up and what pulled it down."""
    tx = "#f2f2f0" if dark else "#0b0b0b"
    grid = "rgba(255,255,255,.07)" if dark else "rgba(0,0,0,.09)"
    lab = "#8e8e88" if dark else "#4a4a46"

    top = block["current_explanation"]["top"][:10][::-1]
    names = [t["label"] for t in top]
    vals = [t["contribution"] for t in top]
    colours = ["#8DC63F" if v > 0 else "#d86050" for v in vals]

    fig = go.Figure(go.Bar(
        x=vals, y=names, orientation="h",
        marker=dict(color=colours, line=dict(color=tx, width=.4)),
        customdata=[t["value"] for t in top],
        hovertemplate="%{y}<br>value %{customdata:.1f}"
                      "<br>contributes %{x:+.2f} AQI<extra></extra>"))
    fig.add_vline(x=0, line_width=1, line_color=lab)
    fig.update_layout(
        height=320, margin=dict(l=0, r=10, t=6, b=30),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=lab, size=11),
        xaxis=dict(title="contribution to the prediction", gridcolor=grid,
                   range=[min(vals) * 1.15 - .1, max(vals) * 1.15 + .1],
                   tickfont=dict(color=lab), title_font=dict(color=lab, size=10)),
        yaxis=dict(tickfont=dict(color=tx, size=11)),
        hoverlabel=dict(bgcolor="#1a1a1a" if dark else "#ffffff",
                        font_color=tx, bordercolor=grid),
        # Bars grow out from zero on first draw. Plotly needs an explicit
        # frame duration for this; without it they simply appear.
        transition=dict(duration=650, easing="cubic-out"))
    return fig


def pretty_feature(name):
    """Readable labels, mirroring the ones in pipeline/11_explain.py."""
    lookup = {
        "aqi": "AQI now", "aqi_lag_1h": "AQI 1 h ago",
        "aqi_lag_3h": "AQI 3 h ago", "aqi_lag_6h": "AQI 6 h ago",
        "aqi_lag_12h": "AQI 12 h ago", "aqi_lag_24h": "AQI 24 h ago",
        "aqi_lag_48h": "AQI 48 h ago", "aqi_lag_72h": "AQI 72 h ago",
        "aqi_lag_168h": "AQI 1 week ago",
        "aqi_roll_mean_1d": "AQI, 1-day mean",
        "aqi_roll_mean_7d": "AQI, 7-day mean",
        "aqi_roll_max_1d": "AQI, daily peak",
        "aqi_roll_min_1d": "AQI, daily low",
        "aqi_roll_std_1d": "AQI volatility",
        "aqi_trend_6h": "6 h trend", "aqi_trend_24h": "24 h trend",
        "aqi_trend_72h": "72 h trend", "aqi_vs_7d": "vs weekly average",
        "pm2_5": "PM2.5", "pm10": "PM10", "no2": "NO2", "o3": "ozone",
        "co": "CO", "so2": "SO2", "nh3": "ammonia",
        "pm2_5_roll_24h": "PM2.5, daily mean",
        "pm10_roll_24h": "PM10, daily mean",
        "pm2_5_lag_24h": "PM2.5 24 h ago",
        "temperature": "temperature", "humidity": "humidity",
        "pressure": "pressure", "wind_speed": "wind speed",
        "wind_u": "wind, east-west", "wind_v": "wind, north-south",
        "ventilation": "ventilation", "calm_flag": "calm air",
        "temp_range_24h": "24 h temperature range",
        "pressure_trend_24h": "pressure trend",
        "temperature_roll_24h": "temperature, daily mean",
        "pressure_roll_24h": "pressure, daily mean",
        "humidity_roll_24h": "humidity, daily mean",
        "wind_speed_roll_24h": "wind, daily mean",
        "precip_24h": "rain, last 24 h", "precip_72h": "rain, last 72 h",
        "hours_ahead": "hours ahead", "sqrt_hours_ahead": "hours ahead (sqrt)",
        "hour_sin": "hour of day", "hour_cos": "hour of day",
        "month_sin": "time of year", "month_cos": "time of year",
        "season_winter": "winter", "season_summer": "summer",
        "season_monsoon": "monsoon", "season_post_monsoon": "post-monsoon",
    }
    if name.endswith("_x_hours"):
        return pretty_feature(name[:-len("_x_hours")]) + " x lead time"
    return lookup.get(name, name.replace("_", " "))


def card(label, value, sub=""):
    return (f'<div class="card"><div class="lbl">{label}</div>'
            f'<div class="val">{value}</div><div class="sub">{sub}</div></div>')


def spark(series):
    """A 48-hour sparkline, or nothing if there is no history."""
    if not series or len(series) < 5:
        return ""
    lo, hi = min(series), max(series)
    rng = max(hi - lo, 1e-6)
    pts = " ".join("%.1f,%.1f" % (i / (len(series) - 1) * 70,
                                  14 - (v - lo) / rng * 12)
                   for i, v in enumerate(series))
    return (f'<svg viewBox="0 0 70 14" style="width:100%;height:14px;'
            f'margin-top:7px;opacity:.65"><polyline points="{pts}" fill="none" '
            f'stroke="var(--ac)" stroke-width="1.2"/></svg>')


# ---------------------------------------------------------------
# Views
# ---------------------------------------------------------------
def view_overview(data, dark):
    cur = data["current"]
    fc = data["forecast"]

    worst = fc.loc[fc["aqi"].idxmax()]
    if worst["aqi"] >= 150:
        st.markdown(
            f'<div class="alert"><b>Air quality alert</b> &nbsp;AQI reaches '
            f'{int(worst["aqi"])} ({worst["category"]}) at '
            f'{pd.Timestamp(worst["timestamp"]).strftime("%A %H:%M")}. '
            f'Sensitive groups should limit outdoor activity.</div>',
            unsafe_allow_html=True)

    trend = cur.get("trend_24h", cur.get("trend_6h", 0))
    arrow = "↓" if trend < 0 else "↑" if trend > 0 else "→"
    colour = CATEGORY_DOT.get(cur["category"], "#8e8e88")

    left, right = st.columns([1, 3])
    with left:
        st.markdown(
            f'<div class="card"><div class="lbl">RIGHT NOW</div>'
            f'<div style="display:flex;align-items:baseline;gap:10px;margin:10px 0">'
            f'<span class="hero-num">{cur["aqi"]}</span>'
            f'<span style="font-size:14px;color:var(--ac)">{arrow} '
            f'{abs(trend):.0f}</span></div>'
            f'<div><span class="pill"><span class="dot live" '
            f'style="background:{colour}"></span>{cur["category"]}</span></div>'
            f'<div class="sub" style="margin-top:11px">driven by '
            f'{cur["dominant_pollutant"].replace("pm2_5","PM2.5").upper()}'
            f' &middot; vs 24 h ago</div></div>', unsafe_allow_html=True)

    with right:
        a, b, c = st.columns(3)
        a.markdown(card("TEMPERATURE", f'{cur["temperature"]:.0f}°', "Celsius"),
                   unsafe_allow_html=True)
        b.markdown(card("HUMIDITY", f'{cur["humidity"]}%',
                        "Dry" if cur["humidity"] < 50 else "Humid"),
                   unsafe_allow_html=True)
        c.markdown(card("WIND", f'{cur["wind_speed"]:.0f}', "km/h"),
                   unsafe_allow_html=True)

        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
        for col, (_, row) in zip(st.columns(3), data["daily"].iterrows()):
            dc = CATEGORY_DOT.get(row["category"], "#8e8e88")
            col.markdown(
                f'<div class="card"><div class="lbl">DAY +{row["day"]}</div>'
                f'<div class="val">{row["mean_aqi"]}</div>'
                f'<div class="sub"><span class="dot" style="background:{dc}">'
                f'</span>{row["min_aqi"]}&ndash;{row["max_aqi"]}</div></div>',
                unsafe_allow_html=True)

    st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
    st.markdown("##### Next 72 hours")
    bounds = [fc[fc["day"] == d]["timestamp"].iloc[0] for d in (2, 3)
              if len(fc[fc["day"] == d])]
    st.plotly_chart(line_chart(fc["timestamp"], fc["aqi"], dark,
                               height=290, markers=False, dividers=bounds),
                    use_container_width=True, config={"displayModeBar": False})


def view_forecast(data, dark):
    fc = data["forecast"]
    mode = st.radio("View", ["Whole day", "Specific hour"],
                    horizontal=True, label_visibility="collapsed")

    if mode == "Whole day":
        day = st.radio("Day", ["Day +1", "Day +2", "Day +3"],
                       horizontal=True, label_visibility="collapsed")
        block = fc[fc["day"] == int(day[-1])]
        st.plotly_chart(line_chart(block["timestamp"], block["aqi"], dark),
                        use_container_width=True,
                        config={"displayModeBar": False})
    else:
        h = st.slider("Hours ahead", 1, 72, 18, label_visibility="collapsed")
        row = fc[fc["hours_ahead"] == h].iloc[0]
        colour = CATEGORY_DOT.get(row["category"], "#8e8e88")
        when = pd.Timestamp(row["timestamp"])
        c1, c2 = st.columns(2)
        c1.markdown(
            f'<div class="card"><div class="lbl">'
            f'{when.strftime("%A %d %B &middot; %H:%M")} UTC</div>'
            f'<div class="hero-num" style="margin:12px 0">{int(row["aqi"])}</div>'
            f'<div><span class="pill"><span class="dot" '
            f'style="background:{colour}"></span>{row["category"]}</span></div>'
            f'<div class="sub" style="margin-top:10px">{h} hours ahead '
            f'&middot; day +{int(row["day"])} model</div></div>',
            unsafe_allow_html=True)
        with c2:
            st.plotly_chart(gauge(int(row["aqi"]), dark),
                            use_container_width=True,
                            config={"displayModeBar": False})

    # Measured, not forecast - the models predict AQI directly, not the
    # individual pollutants, so this panel does not follow the day
    # selector and the heading has to say so.
    st.markdown("<div style='height:18px'></div>", unsafe_allow_html=True)
    st.markdown("##### Pollutants now")
    st.markdown(f'<div class="foot" style="margin:-8px 0 10px">measured at '
                f'{pd.Timestamp(data["predicted_from"]).strftime("%H:%M")} UTC '
                f'&middot; current readings, not a forecast</div>',
                unsafe_allow_html=True)

    pol = data["current"]["pollutants"]
    hist = data.get("pollutant_history", {})
    names = {"pm2_5": "PM2.5", "pm10": "PM10", "no2": "NO₂",
             "o3": "O₃", "co": "CO", "so2": "SO₂"}
    for col, (k, label) in zip(st.columns(6), names.items()):
        unit = "ppm" if k == "co" else "µg/m³"
        val = pol[k] / 1145 if k == "co" else pol[k]
        col.markdown(
            f'<div class="card" style="padding:13px">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val" style="font-size:22px">{val:.1f}</div>'
            f'<div class="sub">{unit}</div>{spark(hist.get(k))}</div>',
            unsafe_allow_html=True)


def view_accuracy(data, dark):
    st.markdown("##### Model performance")
    st.markdown('<div class="foot" style="margin:-8px 0 14px">R&sup2; on a '
                'held-out test period, per forecast horizon</div>',
                unsafe_allow_html=True)

    for col, key in zip(st.columns(3), ["day1", "day2", "day3"]):
        m = data["models"].get(key, {})
        r2 = m.get("r2") or 0
        pct = int(round(r2 * 100))
        col.markdown(
            f'<div class="card"><div class="lbl">DAY +{key[-1]}</div>'
            f'<div class="val">{pct}<span style="font-size:15px">%</span></div>'
            f'<div class="bar-track"><div class="bar-fill" '
            f'style="width:{pct}%"></div></div>'
            f'<div class="foot">R&sup2; {r2:.3f}<br>'
            f'MAE {m.get("mae") or 0:.1f} &middot; RMSE {m.get("rmse") or 0:.1f}'
            f'<br>{m.get("source","")}</div></div>', unsafe_allow_html=True)

    st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
    st.markdown(
        '<div class="foot">Accuracy falls with lead time, as forecasts '
        'naturally do. Each model is also compared against a persistence '
        'baseline &mdash; predicting that AQI stays exactly as it is now '
        '&mdash; which is a strong benchmark for air quality because it '
        'changes slowly. The models beat it by +0.022, +0.034 and +0.069 '
        'R&sup2; at day +1, +2 and +3, so their advantage grows as '
        'forecasting gets harder.</div>', unsafe_allow_html=True)

    # ---- Explainability ----
    shap_data = read_shap()
    if shap_data is None:
        return

    st.markdown("<div style='height:28px'></div>", unsafe_allow_html=True)
    st.markdown('<div class="shap-head"></div>', unsafe_allow_html=True)
    st.markdown("##### What the models pay attention to")
    st.markdown(
        '<div class="foot" style="margin:-8px 0 14px">SHAP splits a '
        'prediction into the contribution of every feature, and the parts '
        'sum exactly to the result &mdash; so this is the model\'s actual '
        'reasoning, not a guess at it.</div>', unsafe_allow_html=True)

    choice = st.radio("Horizon", ["Day +1", "Day +2", "Day +3"],
                      horizontal=True, label_visibility="collapsed",
                      key="shap_day")
    day = int(choice[-1])
    block = shap_data["horizons"].get("day%d" % day)
    if not block:
        return

    st.markdown('<div class="shap-charts">', unsafe_allow_html=True)
    left, right = st.columns(2)
    with left:
        st.markdown('<div class="foot" style="margin-bottom:4px">'
                    '<b>Overall</b> &middot; averaged across recent forecasts'
                    '</div>', unsafe_allow_html=True)
        st.plotly_chart(shap_importance_chart(block, dark),
                        use_container_width=True,
                        config={"displayModeBar": False})
    with right:
        st.markdown('<div class="foot" style="margin-bottom:4px">'
                    '<b>This forecast</b> &middot; why the next value is what '
                    'it is</div>', unsafe_allow_html=True)
        st.plotly_chart(shap_local_chart(block, dark),
                        use_container_width=True,
                        config={"displayModeBar": False})
    st.markdown('</div>', unsafe_allow_html=True)

    local = block["current_explanation"]
    if block["model"].startswith("XGBoost"):
        headline = ("predicts a change of %+.1f AQI from the current reading"
                    % local["prediction"])
    else:
        headline = ("predicts AQI %.0f, from a baseline of %.0f"
                    % (local["prediction"], local["base"]))
    st.markdown(
        f'<div class="foot">{block["model"]} &middot; explained at '
        f'{block["hours_ahead"]} hours ahead &middot; {headline}.</div>',
        unsafe_allow_html=True)

    st.markdown(
        '<div class="foot" style="margin-top:12px">The two model types '
        'behave differently. The day +1 tree model spreads its attention '
        'across pollutants and weather &mdash; PM2.5, and the 24-hour '
        'temperature range, which signals the inversions that trap smoke '
        'near the ground. The Ridge models lean almost entirely on the '
        'most recent AQI, which is the persistence effect made visible.'
        '</div>', unsafe_allow_html=True)


def view_history(data, dark):
    span = st.radio("Range", ["24 hours", "7 days", "30 days"],
                    horizontal=True, label_visibility="collapsed", index=2)
    hours = {"24 hours": 24, "7 days": 24 * 7, "30 days": 24 * 30}[span]
    hist = data["history"].tail(hours)
    st.plotly_chart(
        line_chart(hist["timestamp"], hist["aqi"], dark, height=340,
                   markers=(hours <= 24)),
        use_container_width=True, config={"displayModeBar": False})

    a, b, c, d = st.columns(4)
    a.markdown(card("AVERAGE", "%d" % hist["aqi"].mean(), "over the period"),
               unsafe_allow_html=True)
    b.markdown(card("HIGHEST", "%d" % hist["aqi"].max(), "peak reading"),
               unsafe_allow_html=True)
    c.markdown(card("LOWEST", "%d" % hist["aqi"].min(), "cleanest hour"),
               unsafe_allow_html=True)
    d.markdown(card("READINGS", "%d" % len(hist), "hourly observations"),
               unsafe_allow_html=True)


# ---------------------------------------------------------------
# Welcome
# ---------------------------------------------------------------
@st.dialog("How this works")
def welcome():
    """
    Shown once per session. The thing that genuinely needs explaining
    is why the pollutants panel does not follow the day selector; the
    rest is a short tour.
    """
    st.markdown("""
**A three-day air quality forecast for Ghotki**, collected hourly and
re-trained every night.

**The four views**

- **Overview** — conditions now, plus the next 72 hours at a glance
- **Forecast** — a whole day at a time, or any single hour you pick
- **Accuracy** — how each model scores, and what drives its predictions
- **History** — what the air has actually been like, 24 hours to 30 days

**Two things worth knowing**

The forecast is rebuilt every night, right after the models retrain, and
the page reads that saved result — so it opens instantly and the numbers
are never more than a day old. The footer shows exactly when the current
forecast was issued.

Pollutant readings are **measured now**, not forecast. The models predict
AQI directly rather than each pollutant, so that panel stays the same
when you switch days.
    """)
    if st.button("Got it"):
        st.rerun()


# ---------------------------------------------------------------
# App
# ---------------------------------------------------------------
def main():
    ss = st.session_state
    ss.setdefault("dark", True)
    # Marked seen as soon as it is shown, not when dismissed. Otherwise
    # switching theme before clicking through re-opens it every rerun.
    ss.setdefault("seen_welcome", False)

    with st.sidebar:
        # Placeholder: the logo has to sit at the top, but its colour
        # depends on the theme radio further down. Rendering it before
        # that radio is read uses the PREVIOUS value, so the first click
        # showed the old logo and it took a second click to catch up.
        # A slot holds the position; the content is written afterwards.
        logo_slot = st.empty()

        view = st.radio("Section", VIEWS, label_visibility="collapsed")

        st.markdown('<div class="side-head">DISPLAY</div>',
                    unsafe_allow_html=True)
        st.markdown('<div class="theme-row">', unsafe_allow_html=True)
        theme = st.radio("Theme", ["Dark", "Light"],
                         index=0 if ss.dark else 1,
                         horizontal=True, label_visibility="collapsed")
        st.markdown('</div>', unsafe_allow_html=True)

        # Rerun the moment the theme changes.
        #
        # Streamlit renders widgets in declaration order, and inject_css
        # runs after this whole sidebar block - so on the click that
        # switches the theme, everything above has already been drawn
        # with the old palette and only catches up on the next rerun.
        # That is why switching used to take two clicks. Restarting the
        # script here means the first click is enough; the extra pass is
        # cheap because the snapshot and the logo are both cached.
        if (theme == "Dark") != ss.dark:
            ss.dark = theme == "Dark"
            st.rerun()

        logo_slot.markdown(
            logo_tag(ss.dark)
            + '<div class="logo-sub">AQI PREDICTOR</div>'
              '<div class="logo-loc"><b>&#9679;</b> Ghotki, Sindh '
              '&middot; Pakistan</div>', unsafe_allow_html=True)

        st.markdown('<div class="side-head">ABOUT</div>', unsafe_allow_html=True)
        show_help = st.button("How this works")

    inject_css(ss.dark)

    data = read_snapshot()
    if data is None:
        st.error("No data available. Run "
                 "`python pipeline/10_build_snapshot.py` first.")
        return

    st.markdown(
        '<div class="page-head"><h1>Air Quality Index</h1>'
        '<span class="page-sub">Ghotki, Sindh &middot; Pakistan</span></div>',
        unsafe_allow_html=True)

    {"Overview": view_overview, "Forecast": view_forecast,
     "Accuracy": view_accuracy, "History": view_history}[view](data, ss.dark)

    st.markdown(
        f'<div class="foot" style="margin-top:22px">Forecast issued '
        f'{pd.Timestamp(data["predicted_from"]).strftime("%d %b %Y, %H:%M")} UTC '
        f'&middot; {data["source"]} &middot; models retrained daily via '
        f'GitHub Actions</div>', unsafe_allow_html=True)

    # Dialog last, so the CSS above has already been applied to it
    if show_help or not ss.seen_welcome:
        ss.seen_welcome = True
        welcome()


if __name__ == "__main__":
    main()