"""
10Pearls AQI Predictor - dashboard

Run locally:   streamlit run app/dashboard.py
Deployed on:   Streamlit Community Cloud

Navigation
----------
Views are chosen from the sidebar rather than tabs across the top.
Streamlit's st.tabs cannot be moved into the sidebar, so this uses a
radio styled to look like a nav list - same behaviour, and it keeps the
main area free for content.

Data sources, tried in order
----------------------------
  1. data/dashboard_snapshot.json  - committed to the repo, instant
  2. Hopsworks feature store       - on demand, via the sidebar button

Snapshot first is deliberate. Reading the store takes 15-25 seconds when
it works and times out after ~170 seconds when the free-tier quota is
spent, which would leave a visitor staring at a blank page. The snapshot
is regenerated by the daily training workflow, and the forecast only
changes daily anyway, so it is never meaningfully stale.
"""

import json
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "pipeline"))

SNAPSHOT = ROOT / "data" / "dashboard_snapshot.json"

st.set_page_config(page_title="10Pearls AQI Predictor", page_icon="◐",
                   layout="wide", initial_sidebar_state="expanded")

# The 10Pearls mark as SVG, so it inherits the theme colour and stays
# sharp at any size. A filled disc holds the outlined "1"; the "0" is a
# ring whose outer edge breaks past the disc's right side, which is what
# makes the mark recognisable.
# The 10Pearls mark as SVG, so it inherits the theme colour and stays
# sharp at any size.
#
# Geometry: a filled disc holds the outlined "1"; a knockout circle
# carves the dark gap; the ring on top forms the "0" and breaks past the
# disc's right edge, which is what makes the mark recognisable.
#
# No HTML comments inside the string - Streamlit's markdown sanitiser
# strips them and mangles the surrounding tags, which left the SVG
# rendering as the bare word "Pearls".
LOGO_SVG = ("""<svg class="logo" viewBox="0 0 236 64" """
            """xmlns="http://www.w3.org/2000/svg" role="img" """
            """aria-label="10Pearls">"""
            """<circle cx="33" cy="32" r="29" fill="var(--tx)"/>"""
            """<path d="M18 20 L27 14 L27 50 L18 50 Z" fill="none" """
            """stroke="var(--bg)" stroke-width="3.4"/>"""
            """<circle cx="57" cy="32" r="26" fill="var(--bg)"/>"""
            """<circle cx="57" cy="32" r="20" fill="none" """
            """stroke="var(--tx)" stroke-width="11"/>"""
            """<text x="90" y="46" font-family="Inter,Segoe UI,Helvetica,"""
            """Arial,sans-serif" font-size="42" font-weight="700" """
            """letter-spacing="-1.4" fill="var(--tx)">Pearls</text>"""
            """</svg>""")

LOADER_HTML = """
<div class="load-wrap">
  <div class="load-disc">
    <svg class="walk" viewBox="0 0 40 48" aria-hidden="true">
      <circle cx="20" cy="8" r="4.6" fill="var(--tx)" stroke="none"/>
      <line x1="20" y1="13" x2="18" y2="28"/>
      <line class="arm-a" x1="19" y1="17" x2="28" y2="23"/>
      <line class="arm-b" x1="19" y1="17" x2="11" y2="24"/>
      <line class="leg-a" x1="18" y1="28" x2="26" y2="41"/>
      <line class="leg-b" x1="18" y1="28" x2="11" y2="41"/>
    </svg>
  </div>
  <div class="load-text">Reading the feature store</div>
  <div class="load-note">this usually takes 30&ndash;60 seconds</div>
</div>"""

CATEGORY_DOT = {
    "Good": "#5dcaa5", "Moderate": "#e0c060",
    "Unhealthy for Sensitive Groups": "#e09050", "Unhealthy": "#d86050",
    "Very Unhealthy": "#a070c0", "Hazardous": "#8a4040", "Unknown": "#8e8e88",
}

VIEWS = ["Overview", "Forecast", "Accuracy", "History"]


# ---------------------------------------------------------------
# Styling
# ---------------------------------------------------------------
def inject_css(dark):
    if dark:
        v = dict(bg="#0a0a0a", p1="#141414", p2="#1c1c1a",
                 ln="rgba(255,255,255,.09)", ln2="rgba(255,255,255,.18)",
                 tx="#f2f2f0", dm="#8e8e88", ft="#5c5c57",
                 hov="rgba(255,255,255,.05)")
    else:
        v = dict(bg="#f7f7f5", p1="#ffffff", p2="#efefec",
                 ln="rgba(0,0,0,.08)", ln2="rgba(0,0,0,.18)",
                 tx="#0b0b0b", dm="#5f5f5a", ft="#9a9a94",
                 hov="rgba(0,0,0,.04)")

    ac = "#8DC63F"          # 10Pearls green, used sparingly

    st.markdown(f"""<style>
    :root {{
      --bg:{v['bg']}; --p1:{v['p1']}; --p2:{v['p2']};
      --ln:{v['ln']}; --ln2:{v['ln2']}; --hov:{v['hov']};
      --tx:{v['tx']}; --dm:{v['dm']}; --ft:{v['ft']}; --ac:{ac};
    }}
    .stApp {{ background:var(--bg); color:var(--tx); }}
    [data-testid="stHeader"] {{ background:transparent; }}
    .block-container {{ padding:1.4rem 2.2rem 3rem; max-width:1500px; }}
    #MainMenu, footer {{ visibility:hidden; }}
    h1,h2,h3,h4,h5,p,span,div,label {{ color:var(--tx); }}

    /* ---- Sidebar: flat, no containers, mark sits top-left ---- */
    [data-testid="stSidebar"] {{ background:var(--p1);
                                 border-right:1px solid var(--ln); }}
    [data-testid="stSidebar"] * {{ color:var(--tx); }}
    /* Sits high and reads large, like the Claude sidebar wordmark */
    [data-testid="stSidebar"] > div:first-child {{ padding-top:.55rem; }}
    .logo {{ width:172px; height:auto; display:block; margin:0 0 7px 1px; }}
    .logo-sub {{ font-size:11px; color:var(--dm); letter-spacing:1.4px;
                 margin:0 0 3px 3px; }}
    .logo-loc {{ font-size:11px; color:var(--ft); margin:0 0 24px 3px; }}
    .logo-loc b {{ color:var(--ac); font-weight:400; }}
    .side-head {{ font-size:10px; letter-spacing:1.3px; color:var(--ft);
                  margin:20px 0 7px 3px; }}

    /* Sidebar radio, restyled as a navigation list */
    [data-testid="stSidebar"] div[role="radiogroup"] {{ gap:1px; }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label {{
      background:transparent; border:0; border-radius:8px;
      padding:8px 11px; margin:0; font-size:14px; width:100%;
      transition:background .18s; }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label:hover {{
      background:var(--hov); }}
    [data-testid="stSidebar"] div[role="radiogroup"] > label:has(input:checked) {{
      background:var(--p2); }}
    /* Hide the radio circles - this reads as a menu, not a form */
    [data-testid="stSidebar"] div[role="radiogroup"] label > div:first-child {{
      display:none; }}

    /* Theme switch stays a visible pair of options */
    [data-testid="stSidebar"] .theme-row div[role="radiogroup"] {{
      flex-direction:row; gap:5px; }}

    /* ---- Page heading ---- */
    .page-head {{ margin-bottom:18px; animation:rise .5s ease-out both; }}
    .page-head h1 {{ font-size:31px; font-weight:600; letter-spacing:-1px;
                     margin:0 0 4px; line-height:1.1; }}
    .page-sub {{ font-size:13px; color:var(--dm); }}

    /* ---- Cards ---- */
    .card {{ background:var(--p1); border:1px solid var(--ln);
             border-radius:13px; padding:15px 17px; height:100%;
             transition:border-color .25s, transform .25s;
             animation:rise .45s ease-out both; }}
    .card:hover {{ border-color:var(--ln2); transform:translateY(-2px); }}
    .lbl {{ font-size:10px; color:var(--dm); letter-spacing:.8px; }}
    .val {{ font-size:27px; font-weight:500; letter-spacing:-1.1px;
            margin:7px 0 3px; line-height:1;
            animation:pop .5s cubic-bezier(.34,1.4,.64,1) both .18s; }}
    .sub {{ font-size:10px; color:var(--ft); }}
    .hero-num {{ font-size:52px; font-weight:500; letter-spacing:-2.5px;
                 line-height:1;
                 animation:pop .6s cubic-bezier(.34,1.4,.64,1) both .1s; }}
    .pill {{ font-size:11px; padding:4px 11px; border:1px solid var(--ln2);
             border-radius:99px; display:inline-block; }}
    .dot {{ width:7px; height:7px; border-radius:50%; display:inline-block;
            margin-right:6px; vertical-align:1px; }}
    .dot.live {{ animation:pulse 2.4s ease-in-out infinite; }}
    .alert {{ background:var(--p2); border:1px solid var(--ln2);
              border-left:3px solid #e0c060; border-radius:0 12px 12px 0;
              padding:12px 15px; font-size:13px; margin-bottom:14px;
              animation:rise .45s ease-out both; }}
    .bar-track {{ height:4px; background:var(--bg); border-radius:9px;
                  overflow:hidden; margin:8px 0 9px; }}
    .bar-fill {{ height:100%; background:var(--ac); border-radius:9px;
                 animation:grow .9s cubic-bezier(.4,0,.2,1) both .2s; }}
    .foot {{ font-size:11px; color:var(--ft); line-height:1.7; }}

    [data-testid="column"]:nth-child(2) .card {{ animation-delay:.07s; }}
    [data-testid="column"]:nth-child(3) .card {{ animation-delay:.13s; }}
    [data-testid="column"]:nth-child(4) .card {{ animation-delay:.19s; }}

    /* ---- Motion ---- */
    @keyframes rise {{ from{{opacity:0;transform:translateY(10px)}}
                       to{{opacity:1;transform:translateY(0)}} }}
    @keyframes pop {{ 0%{{opacity:0;transform:scale(.86)}}
                      60%{{transform:scale(1.04)}}
                      100%{{opacity:1;transform:scale(1)}} }}
    @keyframes pulse {{ 0%,100%{{opacity:1;transform:scale(1)}}
                        50%{{opacity:.45;transform:scale(1.35)}} }}
    @keyframes grow {{ from{{width:0 !important}} }}
    @media (prefers-reduced-motion: reduce) {{
      *,*::before,*::after {{ animation-duration:.01ms !important;
                              animation-iteration-count:1 !important; }} }}

    /* ---- Dialog ----
       Rendered in a portal outside .stApp, so it needs its own rules or
       it stays dark when the rest of the page turns light. */
    div[data-testid="stDialog"] > div,
    div[role="dialog"] {{ background:var(--p1) !important;
                          border:1px solid var(--ln) !important;
                          border-radius:14px !important; }}
    div[role="dialog"] * {{ color:var(--tx) !important; }}
    div[role="dialog"] strong {{ color:var(--tx) !important; }}

    /* ---- Loading overlay ----
       Streamlit's own spinner renders inline wherever it is called,
       which put a strip in the sidebar. Styling its internals turned
       out to be brittle - hiding the label also hid the glyph, leaving
       an empty circle - so this is a custom overlay instead, shown in
       a placeholder that is cleared when the fetch returns. */
    .load-wrap {{ position:fixed; inset:0; z-index:9999;
      display:flex; flex-direction:column; align-items:center;
      justify-content:center; gap:16px;
      background:rgba(0,0,0,.5); backdrop-filter:blur(6px);
      -webkit-backdrop-filter:blur(6px); }}
    .load-disc {{ width:92px; height:92px; border-radius:50%;
      background:var(--p1); border:1px solid var(--ln2);
      display:flex; align-items:center; justify-content:center;
      position:relative; }}
    /* A ring sweeping around the figure, so the wait reads as progress */
    .load-disc::before {{ content:""; position:absolute; inset:-1px;
      border-radius:50%; border:2px solid transparent;
      border-top-color:var(--ac); animation:spin 1.1s linear infinite; }}
    @keyframes spin {{ to {{ transform:rotate(360deg); }} }}

    /* The limbs swing in opposite pairs, which is enough to read as
       walking without needing a sprite sheet. */
    .walk {{ width:40px; height:48px; }}
    .walk line, .walk path {{ stroke:var(--tx); stroke-width:2.6;
      stroke-linecap:round; fill:none; }}
    .walk .leg-a {{ transform-origin:18px 28px; animation:swingA .62s ease-in-out infinite alternate; }}
    .walk .leg-b {{ transform-origin:18px 28px; animation:swingB .62s ease-in-out infinite alternate; }}
    .walk .arm-a {{ transform-origin:19px 17px; animation:swingB .62s ease-in-out infinite alternate; }}
    .walk .arm-b {{ transform-origin:19px 17px; animation:swingA .62s ease-in-out infinite alternate; }}
    @keyframes swingA {{ from {{ transform:rotate(-19deg); }}
                         to   {{ transform:rotate(19deg); }} }}
    @keyframes swingB {{ from {{ transform:rotate(19deg); }}
                         to   {{ transform:rotate(-19deg); }} }}
    .load-text {{ font-size:13px; color:var(--tx); }}
    .load-note {{ font-size:11px; color:var(--dm); margin-top:-10px; }}

    .stButton>button {{ background:var(--p2); color:var(--tx);
      border:1px solid var(--ln2); border-radius:8px; font-size:13px;
      font-weight:400; width:100%; transition:all .2s; }}
    .stButton>button:hover {{ border-color:var(--ac); }}
    .stMain div[role="radiogroup"] {{ gap:5px; }}
    .stMain div[role="radiogroup"] label {{ background:var(--p1);
      border:1px solid var(--ln); border-radius:8px; padding:6px 14px;
      font-size:13px; transition:all .2s; }}
    .stMain div[role="radiogroup"] label:hover {{ border-color:var(--ln2); }}
    </style>""", unsafe_allow_html=True)


# ---------------------------------------------------------------
# Data
# ---------------------------------------------------------------
@st.cache_data(show_spinner=False)
def read_snapshot():
    if not SNAPSHOT.exists():
        return None
    with open(SNAPSHOT) as f:
        snap = json.load(f)

    fc = pd.DataFrame(snap["forecast"])
    fc["timestamp"] = pd.to_datetime(fc["timestamp"], utc=True)
    hi = pd.DataFrame(snap["history"])
    hi["timestamp"] = pd.to_datetime(hi["timestamp"], utc=True)

    return {
        "mode": "snapshot", "current": snap["current"], "forecast": fc,
        "daily": pd.DataFrame(snap["daily"]), "history": hi,
        "models": snap["models"],
        "predicted_from": pd.Timestamp(snap["predicted_from"]),
        "source": "snapshot &middot; " + snap["generated_at"][:16].replace("T", " "),
        "pollutant_history": snap.get("pollutant_history", {}),
    }


def read_live():
    """
    Read straight from the feature store. Called only from the sidebar
    button, because it is slow.

    Works both locally and on Streamlit Cloud. An earlier version
    skipped this entirely when deployed, because the first build failed
    on hopsworks - it depends on confluent-kafka, which has no wheel for
    Python 3.14. Pinning the deployment to Python 3.11 fixed the install,
    so the guard was blocking something that works.

    Expect 40-60 seconds: the store read is the slow part, plus the
    model downloads. That is why it is a button and the snapshot is the
    default.
    """
    try:
        import importlib
        predict = importlib.import_module("09_predict")
        forecast, info = predict.forecast(verbose=False)
        daily = predict.daily_summary(forecast)
        df, _ = predict.load_features(verbose=False)
    except Exception as error:
        st.warning("Live read failed (%s). Showing the saved snapshot."
                   % type(error).__name__)
        return None

    latest = df.iloc[-1]
    day_ago = df["aqi"].iloc[-25] if len(df) > 25 else latest["aqi"]
    return {
        "mode": "live",
        "current": {
            "aqi": int(round(latest["aqi"])),
            "category": info["current_category"],
            "dominant_pollutant": info["dominant_pollutant"],
            "trend_24h": round(float(latest["aqi"] - day_ago), 1),
            "temperature": round(float(latest["temperature"]), 1),
            "humidity": int(round(latest["humidity"])),
            "wind_speed": round(float(latest["wind_speed"]), 1),
            "pollutants": {p: round(float(latest[p]), 1)
                           for p in ["pm2_5", "pm10", "no2", "o3", "co", "so2"]},
        },
        "forecast": forecast, "daily": daily,
        "history": df[["timestamp", "aqi"]].tail(24 * 30),
        "models": info["models"],
        "predicted_from": info["predicted_from"],
        "source": "live &middot; " + info["data_source"],
        "pollutant_history": {
            p: [round(float(x), 1) for x in df[p].tail(48).fillna(0)]
            for p in ["pm2_5", "pm10", "no2", "o3", "co", "so2"]},
    }


# ---------------------------------------------------------------
# Charts
# ---------------------------------------------------------------
def line_chart(x, y, dark, height=300, markers=True, dividers=None):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    grid = "rgba(255,255,255,.07)" if dark else "rgba(0,0,0,.09)"
    # Axis labels need real contrast, not the muted --ft grey. Plotly
    # also keeps its own default template colours unless every tickfont
    # is set explicitly, which is why the labels stayed light when the
    # page turned light.
    lab = "#8e8e88" if dark else "#4a4a46"

    lo, hi = min(y), max(y)
    pad = max((hi - lo) * 0.35, 8)
    floor = lo - pad

    fig = go.Figure()
    # Fill to the axis floor, not to zero. tozeroy reaches for y=0 while
    # the axis starts near 85, which drew a slab below the plot.
    fig.add_trace(go.Scatter(
        x=list(x) + list(x)[::-1], y=list(y) + [floor] * len(y),
        mode="lines", line=dict(width=0), fill="toself",
        fillcolor="rgba(141,198,63,.10)", hoverinfo="skip", showlegend=False))
    fig.add_trace(go.Scatter(
        x=x, y=y, mode="lines+markers" if markers else "lines",
        line=dict(color=tx, width=2, shape="spline", smoothing=0.6),
        marker=dict(size=5, color=tx),
        hovertemplate="AQI %{y}<br>%{x|%a %d %b %H:%M}<extra></extra>",
        showlegend=False))

    # No template override: template="none" strips Plotly's default axis
    # configuration along with its colours, which removed the tick labels
    # entirely. Setting every tickfont explicitly is enough to fix the
    # light-mode contrast on its own.
    fig.update_layout(
        height=height, margin=dict(l=0, r=0, t=10, b=0),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=lab, size=11),
        xaxis=dict(showgrid=False, zeroline=False, linecolor=grid,
                   tickfont=dict(color=lab, size=11),
                   title_font=dict(color=lab)),
        yaxis=dict(showgrid=True, gridcolor=grid, zeroline=False,
                   range=[floor, hi + pad],
                   tickfont=dict(color=lab, size=11),
                   title_font=dict(color=lab)),
        hoverlabel=dict(bgcolor="#1a1a1a" if dark else "#ffffff",
                        font_color=tx, bordercolor=grid))

    for d in dividers or []:
        fig.add_vline(x=d, line_width=1, line_dash="dot", line_color=grid)
    return fig


def gauge(value, dark):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    track = "rgba(255,255,255,.1)" if dark else "rgba(0,0,0,.08)"
    lab = "#8e8e88" if dark else "#4a4a46"
    fig = go.Figure(go.Indicator(
        mode="gauge+number", value=value,
        number=dict(font=dict(size=36, color=tx)),
        gauge=dict(axis=dict(range=[0, 200], tickwidth=0,
                             tickfont=dict(size=9, color=lab)),
                   bar=dict(color="#8DC63F", thickness=0.3),
                   bgcolor="rgba(0,0,0,0)", borderwidth=0,
                   steps=[dict(range=[0, 200], color=track)])))
    fig.update_layout(height=190, margin=dict(l=16, r=16, t=8, b=8),
                      paper_bgcolor="rgba(0,0,0,0)", font=dict(color=lab))
    return fig


def card(label, value, sub=""):
    return (f'<div class="card"><div class="lbl">{label}</div>'
            f'<div class="val">{value}</div><div class="sub">{sub}</div></div>')


def spark(series):
    """A 48-hour sparkline, or nothing if there is no history."""
    if not series or len(series) < 5:
        return ""
    lo, hi = min(series), max(series)
    rng = max(hi - lo, 1e-6)
    pts = " ".join("%.1f,%.1f" % (i / (len(series) - 1) * 70,
                                  14 - (v - lo) / rng * 12)
                   for i, v in enumerate(series))
    return (f'<svg viewBox="0 0 70 14" style="width:100%;height:14px;'
            f'margin-top:7px;opacity:.65"><polyline points="{pts}" fill="none" '
            f'stroke="var(--ac)" stroke-width="1.2"/></svg>')


# ---------------------------------------------------------------
# Views
# ---------------------------------------------------------------
def view_overview(data, dark):
    cur = data["current"]
    fc = data["forecast"]

    worst = fc.loc[fc["aqi"].idxmax()]
    if worst["aqi"] >= 150:
        st.markdown(
            f'<div class="alert"><b>Air quality alert</b> &nbsp;AQI reaches '
            f'{int(worst["aqi"])} ({worst["category"]}) at '
            f'{pd.Timestamp(worst["timestamp"]).strftime("%A %H:%M")}. '
            f'Sensitive groups should limit outdoor activity.</div>',
            unsafe_allow_html=True)

    trend = cur.get("trend_24h", cur.get("trend_6h", 0))
    arrow = "↓" if trend < 0 else "↑" if trend > 0 else "→"
    colour = CATEGORY_DOT.get(cur["category"], "#8e8e88")

    left, right = st.columns([1, 3])
    with left:
        st.markdown(
            f'<div class="card"><div class="lbl">RIGHT NOW</div>'
            f'<div style="display:flex;align-items:baseline;gap:10px;margin:10px 0">'
            f'<span class="hero-num">{cur["aqi"]}</span>'
            f'<span style="font-size:14px;color:var(--ac)">{arrow} '
            f'{abs(trend):.0f}</span></div>'
            f'<div><span class="pill"><span class="dot live" '
            f'style="background:{colour}"></span>{cur["category"]}</span></div>'
            f'<div class="sub" style="margin-top:11px">driven by '
            f'{cur["dominant_pollutant"].replace("pm2_5","PM2.5").upper()}'
            f' &middot; vs 24 h ago</div></div>', unsafe_allow_html=True)

    with right:
        a, b, c = st.columns(3)
        a.markdown(card("TEMPERATURE", f'{cur["temperature"]:.0f}°', "Celsius"),
                   unsafe_allow_html=True)
        b.markdown(card("HUMIDITY", f'{cur["humidity"]}%',
                        "Dry" if cur["humidity"] < 50 else "Humid"),
                   unsafe_allow_html=True)
        c.markdown(card("WIND", f'{cur["wind_speed"]:.0f}', "km/h"),
                   unsafe_allow_html=True)

        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
        for col, (_, row) in zip(st.columns(3), data["daily"].iterrows()):
            dc = CATEGORY_DOT.get(row["category"], "#8e8e88")
            col.markdown(
                f'<div class="card"><div class="lbl">DAY +{row["day"]}</div>'
                f'<div class="val">{row["mean_aqi"]}</div>'
                f'<div class="sub"><span class="dot" style="background:{dc}">'
                f'</span>{row["min_aqi"]}&ndash;{row["max_aqi"]}</div></div>',
                unsafe_allow_html=True)

    st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
    st.markdown("##### Next 72 hours")
    bounds = [fc[fc["day"] == d]["timestamp"].iloc[0] for d in (2, 3)
              if len(fc[fc["day"] == d])]
    st.plotly_chart(line_chart(fc["timestamp"], fc["aqi"], dark,
                               height=290, markers=False, dividers=bounds),
                    use_container_width=True, config={"displayModeBar": False})


def view_forecast(data, dark):
    fc = data["forecast"]
    mode = st.radio("View", ["Whole day", "Specific hour"],
                    horizontal=True, label_visibility="collapsed")

    if mode == "Whole day":
        day = st.radio("Day", ["Day +1", "Day +2", "Day +3"],
                       horizontal=True, label_visibility="collapsed")
        block = fc[fc["day"] == int(day[-1])]
        st.plotly_chart(line_chart(block["timestamp"], block["aqi"], dark),
                        use_container_width=True,
                        config={"displayModeBar": False})
    else:
        h = st.slider("Hours ahead", 1, 72, 18, label_visibility="collapsed")
        row = fc[fc["hours_ahead"] == h].iloc[0]
        colour = CATEGORY_DOT.get(row["category"], "#8e8e88")
        when = pd.Timestamp(row["timestamp"])
        c1, c2 = st.columns(2)
        c1.markdown(
            f'<div class="card"><div class="lbl">'
            f'{when.strftime("%A %d %B &middot; %H:%M")} UTC</div>'
            f'<div class="hero-num" style="margin:12px 0">{int(row["aqi"])}</div>'
            f'<div><span class="pill"><span class="dot" '
            f'style="background:{colour}"></span>{row["category"]}</span></div>'
            f'<div class="sub" style="margin-top:10px">{h} hours ahead '
            f'&middot; day +{int(row["day"])} model</div></div>',
            unsafe_allow_html=True)
        with c2:
            st.plotly_chart(gauge(int(row["aqi"]), dark),
                            use_container_width=True,
                            config={"displayModeBar": False})

    # Measured, not forecast - the models predict AQI directly, not the
    # individual pollutants, so this panel does not follow the day
    # selector and the heading has to say so.
    st.markdown("<div style='height:18px'></div>", unsafe_allow_html=True)
    st.markdown("##### Pollutants now")
    st.markdown(f'<div class="foot" style="margin:-8px 0 10px">measured at '
                f'{pd.Timestamp(data["predicted_from"]).strftime("%H:%M")} UTC '
                f'&middot; current readings, not a forecast</div>',
                unsafe_allow_html=True)

    pol = data["current"]["pollutants"]
    hist = data.get("pollutant_history", {})
    names = {"pm2_5": "PM2.5", "pm10": "PM10", "no2": "NO₂",
             "o3": "O₃", "co": "CO", "so2": "SO₂"}
    for col, (k, label) in zip(st.columns(6), names.items()):
        unit = "ppm" if k == "co" else "µg/m³"
        val = pol[k] / 1145 if k == "co" else pol[k]
        col.markdown(
            f'<div class="card" style="padding:13px">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val" style="font-size:22px">{val:.1f}</div>'
            f'<div class="sub">{unit}</div>{spark(hist.get(k))}</div>',
            unsafe_allow_html=True)


def view_accuracy(data, dark):
    st.markdown("##### Model performance")
    st.markdown('<div class="foot" style="margin:-8px 0 14px">R&sup2; on a '
                'held-out test period, per forecast horizon</div>',
                unsafe_allow_html=True)

    for col, key in zip(st.columns(3), ["day1", "day2", "day3"]):
        m = data["models"].get(key, {})
        r2 = m.get("r2") or 0
        pct = int(round(r2 * 100))
        col.markdown(
            f'<div class="card"><div class="lbl">DAY +{key[-1]}</div>'
            f'<div class="val">{pct}<span style="font-size:15px">%</span></div>'
            f'<div class="bar-track"><div class="bar-fill" '
            f'style="width:{pct}%"></div></div>'
            f'<div class="foot">R&sup2; {r2:.3f}<br>'
            f'MAE {m.get("mae") or 0:.1f} &middot; RMSE {m.get("rmse") or 0:.1f}'
            f'<br>{m.get("source","")}</div></div>', unsafe_allow_html=True)

    st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
    st.markdown(
        '<div class="foot">Accuracy falls with lead time, as forecasts '
        'naturally do. Each model is also compared against a persistence '
        'baseline &mdash; predicting that AQI stays exactly as it is now '
        '&mdash; which is a strong benchmark for air quality because it '
        'changes slowly. The models beat it by +0.022, +0.034 and +0.069 '
        'R&sup2; at day +1, +2 and +3, so their advantage grows as '
        'forecasting gets harder.</div>', unsafe_allow_html=True)


def view_history(data, dark):
    span = st.radio("Range", ["24 hours", "7 days", "30 days"],
                    horizontal=True, label_visibility="collapsed", index=2)
    hours = {"24 hours": 24, "7 days": 24 * 7, "30 days": 24 * 30}[span]
    hist = data["history"].tail(hours)
    st.plotly_chart(
        line_chart(hist["timestamp"], hist["aqi"], dark, height=340,
                   markers=(hours <= 24)),
        use_container_width=True, config={"displayModeBar": False})

    a, b, c, d = st.columns(4)
    a.markdown(card("AVERAGE", "%d" % hist["aqi"].mean(), "over the period"),
               unsafe_allow_html=True)
    b.markdown(card("HIGHEST", "%d" % hist["aqi"].max(), "peak reading"),
               unsafe_allow_html=True)
    c.markdown(card("LOWEST", "%d" % hist["aqi"].min(), "cleanest hour"),
               unsafe_allow_html=True)
    d.markdown(card("READINGS", "%d" % len(hist), "hourly observations"),
               unsafe_allow_html=True)


# ---------------------------------------------------------------
# Welcome
# ---------------------------------------------------------------
@st.dialog("How this works")
def welcome():
    """
    Shown once per session. Two things genuinely need explaining: why
    "Fetch live data" is slow, and why the pollutants panel does not
    follow the day selector. The rest is a short tour.
    """
    st.markdown("""
**A three-day air quality forecast for Ghotki**, collected hourly and
re-trained every night.

**The four views**

- **Overview** — conditions now, plus the next 72 hours at a glance
- **Forecast** — a whole day at a time, or any single hour you pick
- **Accuracy** — how each model scores, and why that falls with distance
- **History** — what the air has actually been like, 24 hours to 30 days

**Two things worth knowing**

The page loads from a saved snapshot, refreshed automatically after each
nightly training run, so it opens instantly. **Fetch live data** in the
sidebar reads the feature store directly instead — that takes **30 to 60
seconds**, and longer when the service is busy, which is why it is a
button rather than something that happens on every visit.

Pollutant readings are **measured now**, not forecast. The models predict
AQI directly rather than each pollutant, so that panel stays the same
when you switch days.
    """)
    if st.button("Got it"):
        st.rerun()


# ---------------------------------------------------------------
# App
# ---------------------------------------------------------------
def main():
    ss = st.session_state
    ss.setdefault("dark", True)
    ss.setdefault("live", None)
    # Marked seen as soon as it is shown, not when dismissed. Otherwise
    # switching theme before clicking through re-opens it every rerun.
    ss.setdefault("seen_welcome", False)
    ss.setdefault("fetching", False)

    with st.sidebar:
        st.markdown(LOGO_SVG
                    + '<div class="logo-sub">AQI PREDICTOR</div>'
                      '<div class="logo-loc"><b>&#9679;</b> Ghotki, Sindh '
                      '&middot; Pakistan</div>', unsafe_allow_html=True)

        view = st.radio("Section", VIEWS, label_visibility="collapsed")

        st.markdown('<div class="side-head">DISPLAY</div>',
                    unsafe_allow_html=True)
        st.markdown('<div class="theme-row">', unsafe_allow_html=True)
        theme = st.radio("Theme", ["Dark", "Light"],
                         index=0 if ss.dark else 1,
                         horizontal=True, label_visibility="collapsed")
        st.markdown('</div>', unsafe_allow_html=True)
        ss.dark = theme == "Dark"

        st.markdown('<div class="side-head">DATA</div>', unsafe_allow_html=True)
        show_help = st.button("How this works")
        fetch = st.button("Fetch live data")

    inject_css(ss.dark)

    # The fetch runs on the NEXT rerun, flagged in session state rather
    # than executed inline. Switching theme mid-fetch triggers a rerun
    # that would otherwise abandon the blocking call and leave the
    # overlay stranded; with a flag the overlay simply redraws, in the
    # new theme, and the fetch resumes.
    if fetch:
        ss.fetching = True
        st.rerun()

    if ss.fetching:
        overlay = st.empty()
        overlay.markdown(LOADER_HTML, unsafe_allow_html=True)
        ss.live = read_live()
        ss.fetching = False
        overlay.empty()
        st.rerun()

    data = ss.live or read_snapshot()
    if data is None:
        st.error("No data available. Run "
                 "`python pipeline/10_build_snapshot.py` first.")
        return

    st.markdown(
        '<div class="page-head"><h1>Air Quality Index</h1>'
        '<span class="page-sub">Ghotki, Sindh &middot; Pakistan</span></div>',
        unsafe_allow_html=True)

    {"Overview": view_overview, "Forecast": view_forecast,
     "Accuracy": view_accuracy, "History": view_history}[view](data, ss.dark)

    st.markdown(
        f'<div class="foot" style="margin-top:22px">Forecast issued '
        f'{pd.Timestamp(data["predicted_from"]).strftime("%d %b %Y, %H:%M")} UTC '
        f'&middot; {data["source"]} &middot; models retrained daily via '
        f'GitHub Actions</div>', unsafe_allow_html=True)

    # Dialog last, so the CSS above has already been applied to it
    if show_help or not ss.seen_welcome:
        ss.seen_welcome = True
        welcome()


if __name__ == "__main__":
    main()