"""
10Pearls AQI Predictor - dashboard

Run locally:   streamlit run app/dashboard.py
Deployed on:   Streamlit Community Cloud

Layout
------
Four real tabs rather than a single long page with side-by-side
columns. The earlier version put the forecast chart beside a stack of
accuracy and pollutant cards; when the accuracy panel expanded, the
right column grew far taller than the left and left a large empty gap
under the chart. Tabs remove the problem entirely - each pane is full
width, so nothing has to line up against anything else.

Data sources, tried in order
----------------------------
  1. data/dashboard_snapshot.json  - committed to the repo, instant
  2. Hopsworks feature store       - on demand, via Refresh

Snapshot first is deliberate. Reading the store takes 15-25 seconds
when it works and times out after ~170 seconds when the free-tier
quota is spent, which would leave a visitor staring at a blank page.
The snapshot is regenerated by the daily training workflow, and the
forecast only changes daily anyway, so it is never meaningfully stale.
"""

import json
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "pipeline"))

SNAPSHOT = ROOT / "data" / "dashboard_snapshot.json"

st.set_page_config(page_title="10Pearls AQI Predictor", page_icon="◐",
                   layout="wide", initial_sidebar_state="expanded")

CATEGORY_DOT = {
    "Good": "#5dcaa5", "Moderate": "#e0c060",
    "Unhealthy for Sensitive Groups": "#e09050", "Unhealthy": "#d86050",
    "Very Unhealthy": "#a070c0", "Hazardous": "#8a4040", "Unknown": "#8e8e88",
}


# ---------------------------------------------------------------
# Styling
# ---------------------------------------------------------------
def inject_css(dark):
    if dark:
        v = dict(bg="#0a0a0a", p1="#141414", p2="#1c1c1a",
                 ln="rgba(255,255,255,.09)", ln2="rgba(255,255,255,.18)",
                 tx="#f2f2f0", dm="#8e8e88", ft="#5c5c57")
        dotc = "rgba(255,255,255,.30)"
    else:
        v = dict(bg="#f7f7f5", p1="#ffffff", p2="#efefec",
                 ln="rgba(0,0,0,.08)", ln2="rgba(0,0,0,.18)",
                 tx="#0b0b0b", dm="#5f5f5a", ft="#9a9a94")
        dotc = "rgba(0,0,0,.22)"

    # 10Pearls' green, used only for the active tab, the location pin,
    # chart fills and progress bars. Everything else stays monochrome,
    # which is how the brand itself reads.
    ac = "#8DC63F"

    st.markdown(f"""<style>
    :root {{
      --bg:{v['bg']}; --p1:{v['p1']}; --p2:{v['p2']};
      --ln:{v['ln']}; --ln2:{v['ln2']};
      --tx:{v['tx']}; --dm:{v['dm']}; --ft:{v['ft']}; --ac:{ac};
    }}
    .stApp {{ background: var(--bg); color: var(--tx); }}
    [data-testid="stHeader"] {{ background: transparent; }}
    [data-testid="stSidebar"] {{ background: var(--p1);
                                 border-right: 1px solid var(--ln); }}
    [data-testid="stSidebar"] * {{ color: var(--tx); }}
    .block-container {{ padding: 1.1rem 2rem 3rem; max-width: 1500px; }}
    #MainMenu, footer {{ visibility: hidden; }}
    h1,h2,h3,h4,h5,p,span,div,label {{ color: var(--tx); }}

    /* ---- Sidebar hero: CSS-only drifting particle field ---- */
    .side-hero {{ position:relative; border-radius:13px; overflow:hidden;
      background:var(--p2); border:1px solid var(--ln);
      padding:20px 15px 16px; margin-bottom:16px; }}
    .side-hero::before {{ content:""; position:absolute; inset:-50%;
      background-image:
        radial-gradient(1.5px 1.5px at 20% 30%, {dotc} 50%, transparent 50%),
        radial-gradient(1px 1px at 70% 20%, {dotc} 50%, transparent 50%),
        radial-gradient(1.5px 1.5px at 45% 70%, {dotc} 50%, transparent 50%),
        radial-gradient(1px 1px at 85% 60%, {dotc} 50%, transparent 50%),
        radial-gradient(1.5px 1.5px at 15% 85%, {dotc} 50%, transparent 50%);
      background-size:160px 160px,120px 120px,200px 200px,140px 140px,180px 180px;
      animation:drift 34s linear infinite; pointer-events:none; }}
    @keyframes drift {{ 0%{{transform:translate(0,0)}}
      50%{{transform:translate(-24px,-15px)}} 100%{{transform:translate(0,0)}} }}
    .side-in {{ position:relative; z-index:1; }}
    .side-mark {{ font-size:25px; font-weight:500; letter-spacing:-.8px;
                  display:flex; align-items:center; }}
    .side-dot {{ width:18px; height:18px; border-radius:50%;
                 background:var(--tx); margin:0 2px; position:relative; top:1px; }}
    .side-tag {{ font-size:10px; color:var(--dm); letter-spacing:1.4px;
                 margin-top:7px; }}
    .side-loc {{ font-size:11px; color:var(--ft); margin-top:13px; }}
    .side-loc b {{ color:var(--ac); font-weight:400; }}
    .side-head {{ font-size:10px; letter-spacing:1.4px; color:var(--ft);
                  margin:16px 0 7px 2px; }}

    /* ---- Cards ---- */
    .card {{ background:var(--p1); border:1px solid var(--ln);
             border-radius:13px; padding:15px 17px;
             transition:border-color .25s, transform .25s; height:100%; }}
    .card:hover {{ border-color:var(--ln2); transform:translateY(-2px); }}
    .lbl {{ font-size:10px; color:var(--dm); letter-spacing:.8px; }}
    .val {{ font-size:27px; font-weight:500; letter-spacing:-1.1px;
            margin:7px 0 3px; line-height:1; }}
    .sub {{ font-size:10px; color:var(--ft); }}
    .hero-num {{ font-size:52px; font-weight:500; letter-spacing:-2.5px;
                 line-height:1; }}
    .pill {{ font-size:11px; padding:4px 11px; border:1px solid var(--ln2);
             border-radius:99px; display:inline-block; }}
    .dot {{ width:7px; height:7px; border-radius:50%; display:inline-block;
            margin-right:6px; vertical-align:1px; }}
    .alert {{ background:var(--p2); border:1px solid var(--ln2);
              border-left:3px solid #e0c060; border-radius:0 12px 12px 0;
              padding:12px 15px; font-size:13px; margin-bottom:14px; }}
    .bar-track {{ height:4px; background:var(--bg); border-radius:9px;
                  overflow:hidden; margin:8px 0 9px; }}
    .bar-fill {{ height:100%; background:var(--ac); border-radius:9px; }}
    .foot {{ font-size:11px; color:var(--ft); line-height:1.7; }}

    /* ---- Real tabs ---- */
    [data-testid="stTabs"] [data-baseweb="tab-list"] {{
      gap:2px; border-bottom:1px solid var(--ln); }}
    [data-testid="stTabs"] [data-baseweb="tab"] {{
      background:transparent; border-radius:0; padding:9px 16px;
      font-size:13px; color:var(--ft); }}
    [data-testid="stTabs"] [aria-selected="true"] {{
      color:var(--tx); border-bottom:2px solid var(--ac); }}
    [data-testid="stTabs"] [data-baseweb="tab-highlight"] {{ display:none; }}

    .stButton>button {{ background:var(--p2); color:var(--tx);
      border:1px solid var(--ln2); border-radius:8px; font-size:13px;
      font-weight:400; width:100%; transition:all .2s; }}
    .stButton>button:hover {{ border-color:var(--ac); }}
    div[role="radiogroup"] {{ gap:5px; }}
    div[role="radiogroup"] label {{ background:var(--p1);
      border:1px solid var(--ln); border-radius:8px; padding:6px 14px;
      font-size:13px; transition:all .2s; }}
    div[role="radiogroup"] label:hover {{ border-color:var(--ln2); }}
    </style>""", unsafe_allow_html=True)


# ---------------------------------------------------------------
# Data
# ---------------------------------------------------------------
@st.cache_data(show_spinner=False)
def read_snapshot():
    if not SNAPSHOT.exists():
        return None
    with open(SNAPSHOT) as f:
        snap = json.load(f)

    fc = pd.DataFrame(snap["forecast"])
    fc["timestamp"] = pd.to_datetime(fc["timestamp"], utc=True)
    hi = pd.DataFrame(snap["history"])
    hi["timestamp"] = pd.to_datetime(hi["timestamp"], utc=True)

    return {
        "mode": "snapshot", "current": snap["current"], "forecast": fc,
        "daily": pd.DataFrame(snap["daily"]), "history": hi,
        "models": snap["models"],
        "predicted_from": pd.Timestamp(snap["predicted_from"]),
        "source": "snapshot &middot; " + snap["generated_at"][:16].replace("T", " "),
        "pollutant_history": snap.get("pollutant_history", {}),
    }


@st.cache_data(ttl=900, show_spinner="Reading Hopsworks…")
def read_live():
    """Only called from the Refresh button - see the module docstring."""
    try:
        import importlib
        predict = importlib.import_module("09_predict")
        forecast, info = predict.forecast(verbose=False)
        daily = predict.daily_summary(forecast)
        df, _ = predict.load_features(verbose=False)
    except Exception as error:
        st.warning("Live read failed (%s). Showing the saved snapshot."
                   % type(error).__name__)
        return None

    latest = df.iloc[-1]
    day_ago = df["aqi"].iloc[-25] if len(df) > 25 else latest["aqi"]
    return {
        "mode": "live",
        "current": {
            "aqi": int(round(latest["aqi"])),
            "category": info["current_category"],
            "dominant_pollutant": info["dominant_pollutant"],
            "trend_24h": round(float(latest["aqi"] - day_ago), 1),
            "temperature": round(float(latest["temperature"]), 1),
            "humidity": int(round(latest["humidity"])),
            "wind_speed": round(float(latest["wind_speed"]), 1),
            "pollutants": {p: round(float(latest[p]), 1)
                           for p in ["pm2_5", "pm10", "no2", "o3", "co", "so2"]},
        },
        "forecast": forecast, "daily": daily,
        "history": df[["timestamp", "aqi"]].tail(24 * 30),
        "models": info["models"],
        "predicted_from": info["predicted_from"],
        "source": "live &middot; " + info["data_source"],
        "pollutant_history": {
            p: [round(float(x), 1) for x in df[p].tail(48).fillna(0)]
            for p in ["pm2_5", "pm10", "no2", "o3", "co", "so2"]},
    }


# ---------------------------------------------------------------
# Charts
# ---------------------------------------------------------------
def line_chart(x, y, dark, height=300, markers=True, dividers=None):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    grid = "rgba(255,255,255,.07)" if dark else "rgba(0,0,0,.07)"
    ft = "#5c5c57" if dark else "#9a9a94"

    lo, hi = min(y), max(y)
    pad = max((hi - lo) * 0.35, 8)
    floor = lo - pad

    fig = go.Figure()
    # Fill to the axis floor, not to zero. tozeroy reaches for y=0 while
    # the axis starts near 85, which drew a slab below the plot.
    fig.add_trace(go.Scatter(
        x=list(x) + list(x)[::-1], y=list(y) + [floor] * len(y),
        mode="lines", line=dict(width=0), fill="toself",
        fillcolor="rgba(141,198,63,.10)", hoverinfo="skip", showlegend=False))
    fig.add_trace(go.Scatter(
        x=x, y=y, mode="lines+markers" if markers else "lines",
        line=dict(color=tx, width=2, shape="spline", smoothing=0.6),
        marker=dict(size=5, color=tx),
        hovertemplate="AQI %{y}<br>%{x|%a %d %b %H:%M}<extra></extra>",
        showlegend=False))

    fig.update_layout(
        height=height, margin=dict(l=0, r=0, t=10, b=0),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=ft, size=11),
        xaxis=dict(showgrid=False, zeroline=False, linecolor=grid),
        yaxis=dict(showgrid=True, gridcolor=grid, zeroline=False,
                   range=[floor, hi + pad]),
        hoverlabel=dict(bgcolor="#1a1a1a" if dark else "#ffffff",
                        font_color=tx, bordercolor=grid))

    for d in dividers or []:
        fig.add_vline(x=d, line_width=1, line_dash="dot", line_color=grid)
    return fig


def gauge(value, dark):
    tx = "#f2f2f0" if dark else "#0b0b0b"
    track = "rgba(255,255,255,.1)" if dark else "rgba(0,0,0,.08)"
    fig = go.Figure(go.Indicator(
        mode="gauge+number", value=value,
        number=dict(font=dict(size=36, color=tx)),
        gauge=dict(axis=dict(range=[0, 200], tickwidth=0,
                             tickfont=dict(size=9, color=track)),
                   bar=dict(color="#8DC63F", thickness=0.3),
                   bgcolor="rgba(0,0,0,0)", borderwidth=0,
                   steps=[dict(range=[0, 200], color=track)])))
    fig.update_layout(height=190, margin=dict(l=16, r=16, t=8, b=8),
                      paper_bgcolor="rgba(0,0,0,0)", font=dict(color=tx))
    return fig


def card(label, value, sub=""):
    return (f'<div class="card"><div class="lbl">{label}</div>'
            f'<div class="val">{value}</div><div class="sub">{sub}</div></div>')


# ---------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------
def tab_overview(data, dark):
    cur = data["current"]
    fc = data["forecast"]

    worst = fc.loc[fc["aqi"].idxmax()]
    if worst["aqi"] >= 150:
        st.markdown(
            f'<div class="alert"><b>Air quality alert</b> &nbsp;AQI reaches '
            f'{int(worst["aqi"])} ({worst["category"]}) at '
            f'{pd.Timestamp(worst["timestamp"]).strftime("%A %H:%M")}. '
            f'Sensitive groups should limit outdoor activity.</div>',
            unsafe_allow_html=True)

    trend = cur.get("trend_24h", cur.get("trend_6h", 0))
    arrow = "↓" if trend < 0 else "↑" if trend > 0 else "→"
    colour = CATEGORY_DOT.get(cur["category"], "#8e8e88")

    left, right = st.columns([1, 3])
    with left:
        st.markdown(
            f'<div class="card"><div class="lbl">RIGHT NOW</div>'
            f'<div style="display:flex;align-items:baseline;gap:10px;margin:10px 0">'
            f'<span class="hero-num">{cur["aqi"]}</span>'
            f'<span style="font-size:14px;color:var(--ac)">{arrow} '
            f'{abs(trend):.0f}</span></div>'
            f'<div><span class="pill"><span class="dot" '
            f'style="background:{colour}"></span>{cur["category"]}</span></div>'
            f'<div class="sub" style="margin-top:11px">driven by '
            f'{cur["dominant_pollutant"].replace("pm2_5","PM2.5").upper()}'
            f' &middot; vs 24 h ago</div></div>', unsafe_allow_html=True)

    with right:
        a, b, c = st.columns(3)
        a.markdown(card("TEMPERATURE", f'{cur["temperature"]:.0f}°', "Celsius"),
                   unsafe_allow_html=True)
        b.markdown(card("HUMIDITY", f'{cur["humidity"]}%',
                        "Dry" if cur["humidity"] < 50 else "Humid"),
                   unsafe_allow_html=True)
        c.markdown(card("WIND", f'{cur["wind_speed"]:.0f}', "km/h"),
                   unsafe_allow_html=True)

        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
        cols = st.columns(3)
        for col, (_, row) in zip(cols, data["daily"].iterrows()):
            dc = CATEGORY_DOT.get(row["category"], "#8e8e88")
            col.markdown(
                f'<div class="card"><div class="lbl">DAY +{row["day"]}</div>'
                f'<div class="val">{row["mean_aqi"]}</div>'
                f'<div class="sub"><span class="dot" style="background:{dc}">'
                f'</span>{row["min_aqi"]}&ndash;{row["max_aqi"]}</div></div>',
                unsafe_allow_html=True)

    st.markdown("<div style='height:18px'></div>", unsafe_allow_html=True)
    st.markdown("##### Next 72 hours")
    bounds = [fc[fc["day"] == d]["timestamp"].iloc[0] for d in (2, 3)
              if len(fc[fc["day"] == d])]
    st.plotly_chart(line_chart(fc["timestamp"], fc["aqi"], dark,
                               height=280, markers=False, dividers=bounds),
                    use_container_width=True, config={"displayModeBar": False})


def tab_forecast(data, dark):
    fc = data["forecast"]
    mode = st.radio("View", ["Whole day", "Specific hour"],
                    horizontal=True, label_visibility="collapsed")

    if mode == "Whole day":
        day = st.radio("Day", ["Day +1", "Day +2", "Day +3"],
                       horizontal=True, label_visibility="collapsed")
        d = int(day[-1])
        block = fc[fc["day"] == d]
        st.plotly_chart(line_chart(block["timestamp"], block["aqi"], dark),
                        use_container_width=True,
                        config={"displayModeBar": False})
    else:
        h = st.slider("Hours ahead", 1, 72, 18, label_visibility="collapsed")
        row = fc[fc["hours_ahead"] == h].iloc[0]
        colour = CATEGORY_DOT.get(row["category"], "#8e8e88")
        when = pd.Timestamp(row["timestamp"])
        c1, c2 = st.columns([1, 1])
        c1.markdown(
            f'<div class="card"><div class="lbl">'
            f'{when.strftime("%A %d %B &middot; %H:%M")} UTC</div>'
            f'<div class="hero-num" style="margin:12px 0">{int(row["aqi"])}</div>'
            f'<div><span class="pill"><span class="dot" '
            f'style="background:{colour}"></span>{row["category"]}</span></div>'
            f'<div class="sub" style="margin-top:10px">{h} hours ahead '
            f'&middot; day +{int(row["day"])} model</div></div>',
            unsafe_allow_html=True)
        with c2:
            st.plotly_chart(gauge(int(row["aqi"]), dark),
                            use_container_width=True,
                            config={"displayModeBar": False})

    # Measured, not forecast - the models predict AQI directly, not
    # individual pollutants, so this panel does not follow the day
    # selector and the heading has to say so.
    st.markdown("<div style='height:16px'></div>", unsafe_allow_html=True)
    st.markdown("##### Pollutants now")
    st.markdown(f'<div class="foot" style="margin:-8px 0 10px">measured at '
                f'{pd.Timestamp(data["predicted_from"]).strftime("%H:%M")} UTC '
                f'&middot; current readings, not a forecast</div>',
                unsafe_allow_html=True)

    pol = cur_pollutants(data)
    hist = data.get("pollutant_history", {})
    names = {"pm2_5": "PM2.5", "pm10": "PM10", "no2": "NO₂",
             "o3": "O₃", "co": "CO", "so2": "SO₂"}
    cols = st.columns(6)
    for col, (k, label) in zip(cols, names.items()):
        unit = "ppm" if k == "co" else "µg/m³"
        val = pol[k] / 1145 if k == "co" else pol[k]
        col.markdown(
            f'<div class="card" style="padding:13px">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val" style="font-size:22px">{val:.1f}</div>'
            f'<div class="sub">{unit}</div>{spark(hist.get(k))}</div>',
            unsafe_allow_html=True)


def cur_pollutants(data):
    return data["current"]["pollutants"]


def spark(series):
    """A 48-hour sparkline, or nothing if there is no history."""
    if not series or len(series) < 5:
        return ""
    lo, hi = min(series), max(series)
    rng = max(hi - lo, 1e-6)
    pts = " ".join("%.1f,%.1f" % (i / (len(series) - 1) * 70,
                                  14 - (v - lo) / rng * 12)
                   for i, v in enumerate(series))
    return (f'<svg viewBox="0 0 70 14" style="width:100%;height:14px;'
            f'margin-top:7px;opacity:.65"><polyline points="{pts}" fill="none" '
            f'stroke="var(--ac)" stroke-width="1.2"/></svg>')


def tab_accuracy(data, dark):
    st.markdown("##### Model performance")
    st.markdown('<div class="foot" style="margin:-8px 0 12px">R&sup2; on a '
                'held-out test period, per forecast horizon</div>',
                unsafe_allow_html=True)

    cols = st.columns(3)
    for col, key in zip(cols, ["day1", "day2", "day3"]):
        m = data["models"].get(key, {})
        r2 = m.get("r2") or 0
        pct = int(round(r2 * 100))
        col.markdown(
            f'<div class="card"><div class="lbl">DAY +{key[-1]}</div>'
            f'<div class="val">{pct}<span style="font-size:15px">%</span></div>'
            f'<div class="bar-track"><div class="bar-fill" '
            f'style="width:{pct}%"></div></div>'
            f'<div class="foot">R&sup2; {r2:.3f}<br>'
            f'MAE {m.get("mae") or 0:.1f} &middot; RMSE {m.get("rmse") or 0:.1f}'
            f'<br>{m.get("source","")}</div></div>', unsafe_allow_html=True)

    st.markdown("<div style='height:18px'></div>", unsafe_allow_html=True)
    st.markdown(
        '<div class="foot">Accuracy falls with lead time, as forecasts '
        'naturally do. Each model is also compared against a persistence '
        'baseline - predicting that AQI stays exactly as it is now - which '
        'is a strong benchmark for air quality because it changes slowly. '
        'The models beat it by +0.022, +0.034 and +0.069 R&sup2; at day +1, '
        '+2 and +3, so their advantage grows as forecasting gets harder.'
        '</div>', unsafe_allow_html=True)


def tab_history(data, dark):
    span = st.radio("Range", ["24 hours", "7 days", "30 days"],
                    horizontal=True, label_visibility="collapsed", index=2)
    hours = {"24 hours": 24, "7 days": 24 * 7, "30 days": 24 * 30}[span]
    hist = data["history"].tail(hours)
    st.plotly_chart(
        line_chart(hist["timestamp"], hist["aqi"], dark, height=340,
                   markers=(hours <= 24)),
        use_container_width=True, config={"displayModeBar": False})

    c1, c2, c3, c4 = st.columns(4)
    c1.markdown(card("AVERAGE", "%d" % hist["aqi"].mean(), "over the period"),
                unsafe_allow_html=True)
    c2.markdown(card("HIGHEST", "%d" % hist["aqi"].max(), "peak reading"),
                unsafe_allow_html=True)
    c3.markdown(card("LOWEST", "%d" % hist["aqi"].min(), "cleanest hour"),
                unsafe_allow_html=True)
    c4.markdown(card("READINGS", "%d" % len(hist), "hourly observations"),
                unsafe_allow_html=True)


# ---------------------------------------------------------------
# App
# ---------------------------------------------------------------
def main():
    if "dark" not in st.session_state:
        st.session_state.dark = True
    if "live" not in st.session_state:
        st.session_state.live = None

    with st.sidebar:
        st.markdown(
            '<div class="side-hero"><div class="side-in">'
            '<div class="side-mark">1<span class="side-dot"></span>Pearls</div>'
            '<div class="side-tag">AQI PREDICTOR</div>'
            '<div class="side-loc"><b>&#9679;</b> Ghotki, Sindh &middot; Pakistan'
            '</div></div></div>', unsafe_allow_html=True)

        st.markdown('<div class="side-head">DISPLAY</div>',
                    unsafe_allow_html=True)
        theme = st.radio("Theme", ["Dark", "Light"],
                         index=0 if st.session_state.dark else 1,
                         horizontal=True, label_visibility="collapsed")
        st.session_state.dark = theme == "Dark"

        st.markdown('<div class="side-head">DATA</div>', unsafe_allow_html=True)
        if st.button("Fetch live data"):
            st.cache_data.clear()
            st.session_state.live = read_live()
            st.rerun()

    dark = st.session_state.dark
    inject_css(dark)

    data = st.session_state.live or read_snapshot()
    if data is None:
        st.error("No data available. Run "
                 "`python pipeline/10_build_snapshot.py` first.")
        return

    st.markdown(
        '<div style="display:flex;align-items:center;gap:10px;'
        'margin-bottom:12px"><span style="font-size:17px;font-weight:500">'
        'Air Quality Forecast</span><span style="font-size:12px;'
        'color:var(--ft)">&middot; Ghotki, Sindh</span></div>',
        unsafe_allow_html=True)

    t1, t2, t3, t4 = st.tabs(["Overview", "Forecast", "Accuracy", "History"])
    with t1:
        tab_overview(data, dark)
    with t2:
        tab_forecast(data, dark)
    with t3:
        tab_accuracy(data, dark)
    with t4:
        tab_history(data, dark)

    st.markdown(
        f'<div class="foot" style="margin-top:20px">Forecast issued '
        f'{pd.Timestamp(data["predicted_from"]).strftime("%d %b %Y, %H:%M")} UTC '
        f'&middot; {data["source"]} &middot; models retrained daily via '
        f'GitHub Actions</div>', unsafe_allow_html=True)


if __name__ == "__main__":
    main()